### ISSUE TITLE
Display log info at application start-up informing that QuickPerf live is enabled

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf-live#13]

**Comment by guiRagh** [comment]
Display log info with Log4J (log4shell problems are not solved yet so ...) or just print it on the console ?
We can use Spring AOP ? For this issue and for log method Mbean calls ?

**Comment by jeanbisutti** [comment]
With `mvn  dependency:tree`, I checked that `quick-perf-live-springboot2` Maven module does not use `log4j-core` . 

Logback is embedded from `spring-boot-starter-jdbc`:

 [INFO] +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.2.4.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compiler`:
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.2.4.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.2.4.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile


The Logback version depends on  `spring-boot-starter-jdbc` vesion.
` spring-boot-starter-jdbc` is an [optional dependency](https://github.com/quick-perf/quickperf-live/blob/5ca753ee7123e079f05954d41a438834cbde2238/spring-boot-2/pom.xml#L50). So, the ` spring-boot-starter-jdbc` version has to be defined by the application using QuickPerf live. 

For this issue, you could use Commons logging that would log with Logback. An example [here](https://github.com/quick-perf/quickperf-live/blob/5ca753ee7123e079f05954d41a438834cbde2238/spring-boot-2/src/main/java/org/quickperf/web/spring/QuickPerfHttpCallHttpCallInfoLogger.java#L22). A simple solution would be to add a static block in [WebLiveAutoconfiguration class](https://github.com/quick-perf/quickperf-live/blob/main/spring-boot-2/src/main/java/org/quickperf/web/spring/WebLiveAutoconfiguration.java) logging an INFO message.

#14 issue could also use Commons logging. The MBean definitions are [here](https://github.com/quick-perf/quickperf-live/tree/main/spring-boot-2/src/main/java/org/quickperf/web/spring/config).

**Comment by jeanbisutti** [comment]
Fixed with e68f6288475801350eca33a94757336622c63acf thanks to @guiRagh
