### ISSUE TITLE
Test generation of REST API: format JSON of the expected response

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf-live#17]
During test generation, QuickPerf live generates a file containing the expected response body.

WIth REST API, the generated response body has a JSON format. The issue aims at formating the JSON.

The code to add is around [here](https://github.com/quick-perf/quickperf-live/blob/main/spring-boot-2/src/main/java/org/quickperf/web/spring/testgeneration/ExpectedResponseFileGenerator.java#L26).

**Comment by tal66** [comment]
Hi, can i be assigned to this?

To format the json string (`content`), i could use jackson (transitive dependency) like this:

```
        ObjectMapper mapper = new ObjectMapper();
        try {
            Object str = mapper.readValue(content, Object.class);
            String jsonPrettyPrint = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(str);
            content = jsonPrettyPrint;
        } catch (JsonProcessingException e) {
            // do nothing. original content will be used
        }
```
*line 3, `Object str = mapper.readValue(content, Object.class);` is necessary, as using line 4 directly on `content` will print out : 
`"{\"key\": \"val\"}"`
instead of :
```
{
  "key" : "val"
}
```

is this what you mean?

**Comment by jeanbisutti** [comment]
The issue is now assigned to you. Thank you for your help.

Your solution seems great.

Yes, it is this kind of formatting.

For this string:

```
[{"firstName":"Paul","lastName":"Pogba","team":"Manchester United"},{"firstName":"Antoine","lastName":"Griezmann","team":"Barcelona"}]
```

the formatting would be something like this

```
[
  {
    "firstName": "Paul",
    "lastName": "Pogba",
    "team": "Manchester United"
  },
  {
    "firstName": "Antoine",
    "lastName": "Griezmann",
    "team": "Barcelona"
  }
]
```

Some tests [here](https://github.com/quick-perf/quickperf-live/tree/main/spring-boot2-test/src/test/java/testgen/junit4) and [here](https://github.com/quick-perf/quickperf-live/tree/main/spring-boot2-test/src/test/java/testgen/junit5) will fail with the code modifications.  The failing tests have to be adapted by formatting the JSON of .json files (see [this folder](https://github.com/quick-perf/quickperf-live/tree/main/spring-boot2-test/src/test/resources/testgen-expected)).
